<?xml version="1.0"?>
<robot name="bulldog_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find bulldog_description)/urdf/bulldog/wheel.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/bulldog/materials.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find lms1xx)/urdf/sick_lms1xx.urdf.xacro" />
  <xacro:include filename="$(find robotiq_s_model_visualization)/cfg/s-model_articulated_macro.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/sensors/kinect2.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/yuntai.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/cover_plate.urdf.xacro" />
  <property name="M_PI" value="3.141592654"/>
  <xacro:property name="wheel_length" value="0.142" />
  <xacro:property name="wheel_radius" value="0.183" />

  <property name="base_x_size" value="0.85" />
  <property name="base_y_size" value="0.42" />
  <property name="base_z_size" value="0.325" />

  <xacro:macro name="bulldog_robot">
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://bulldog_description/meshes/base_link.stl" />
      </geometry>
      <material name="flat_black" />
    </visual>
    <collision>
      <origin xyz="0 0 ${base_z_size/2.0}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/FlatBlack</material>
  </gazebo>

  <link name="inertial_link">
    <inertial>
      <mass value="40" />
      <origin xyz="0 0 0.1" />
      <inertia ixx="0.7" ixy="-0.03" ixz="-0.15" iyy="2" iyz="-0.01" izz="4" />
    </inertial>
  </link>
  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <link name="top_plate_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://bulldog_description/meshes/top_plate.stl" />
      </geometry>
      <material name="grey" />
    </visual>
  </link>
  <gazebo reference="top_plate_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="top_plate_joint" type="fixed">
    <origin xyz="0.07937 0 0.253" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="top_plate_link" />
  </joint>

  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link" />

  <xacro:bulldog_wheel wheel_prefix="front_left">
    <origin xyz="0.27937 0.285 0.0435" rpy="0 0 0" />
  </xacro:bulldog_wheel>
  <xacro:bulldog_wheel wheel_prefix="front_right">
    <origin xyz="0.27937 -0.285 0.0435" rpy="0 0 0" />
  </xacro:bulldog_wheel>
  <xacro:bulldog_wheel wheel_prefix="rear_left">
    <origin xyz="-0.27937 0.285 0.0435" rpy="0 0 0" />
  </xacro:bulldog_wheel>
  <xacro:bulldog_wheel wheel_prefix="rear_right">
    <origin xyz="-0.27937 -0.285 0.0435" rpy="0 0 0" />
  </xacro:bulldog_wheel>

  <!--xacro:if value="$(optenv BULLDOG_DUAL_UR5_ENABLED true)"-->
    <xacro:installation_plate />
    <xacro:ur5_robot prefix="left_arm_" joint_limited="true"/>
    <joint name="left_arm_base" type="fixed">
      <parent link="installation_plate_link" />
      <child link="left_arm_base_link" />
      <origin xyz="0 0.15945 0.09069" rpy="-0.785 0 0" />
    </joint>
    <xacro:ur5_robot prefix="right_arm_" joint_limited="true"/>
    <joint name="right_arm_base" type="fixed">
      <parent link="installation_plate_link" />
      <child link="right_arm_base_link" />
      <origin xyz="0 -0.15945 0.09069" rpy="-0.785 0 ${M_PI}" />
    </joint>

    <link name="cylinder1">
     <visual>
      <geometry>
       <cylinder length="0.045" radius="0.0062" />
       </geometry>
       <origin xyz="0.086 -0.0143 0.012" rpy="1.57 0 1.57" />
       <material name="black">
       <color rgba="0 0 0 1" />
       </material>
       </visual>
    </link>

    <joint name="cylinder1_joint" type="fixed">
    <parent link="left_gripper_palm" />
    <child link="cylinder1" />
    </joint>

    <link name="cylinder2">
     <visual>
      <geometry>
       <cylinder length="0.045" radius="0.0062" />
       </geometry>
       <origin xyz="0.086 -0.0143 -0.012" rpy="1.57 0 1.57" />
       <material name="black">
       <color rgba="0 0 0 1" />
       </material>
       </visual>
    </link>

    <joint name="cylinder2_joint" type="fixed">
    <parent link="left_gripper_palm" />
    <child link="cylinder2" />
    </joint>

    <link name="cylinder3">
     <visual>
      <geometry>
       <cylinder length="0.045" radius="0.0062" />
       </geometry>
       <origin xyz="0.086 -0.0143 0.012" rpy="1.57 0 1.57" />
       <material name="black">
       <color rgba="0 0 0 1" />
       </material>
       </visual>
    </link>

    <joint name="cylinder3_joint" type="fixed">
    <parent link="right_gripper_palm" />
    <child link="cylinder3" />
    </joint>

<link name="cylinder4">
     <visual>
      <geometry>
       <cylinder length="0.045" radius="0.0062" />
       </geometry>
       <origin xyz="0.086 -0.0143 -0.012" rpy="1.57 0 1.57" />
       <material name="black">
       <color rgba="0 0 0 1" />
       </material>
       </visual>
    </link>

    <joint name="cylinder4_joint" type="fixed">
    <parent link="right_gripper_palm" />
    <child link="cylinder4" />
    </joint>

  <xacro:if value="$(arg laser_enabled)">
    <xacro:laser_plate />
    <sick_lms1xx frame="laser" topic="scan"/>
    <joint name="laser_mount_joint" type="fixed">
      <origin xyz="0.015 0 0.044" rpy="${M_PI} 0 0" />
      <parent link="laser_plate_link" />
      <child link="laser" />
    </joint>
  </xacro:if>

  <xacro:s-model_articulated prefix="left_gripper_"/>
  <joint name="left_arm_gripper" type="fixed">
    <parent link="left_arm_ee_link" />
    <child link="left_gripper_palm" />
    <origin xyz="0 0 0" rpy="0 3.14 -1.57" />
  </joint>
  <xacro:s-model_articulated prefix="right_gripper_"/>
  <joint name="right_arm_gripper" type="fixed">
    <parent link="right_arm_ee_link" />
    <child link="right_gripper_palm" />
    <origin xyz="0 0 0" rpy="0 3.14 -1.57" />
  </joint>

  <joint name="yuntai_installation_plate_joint" type="fixed">
    <origin xyz="0.1775 0 0.448 " rpy="-1.5707 0 1.5707" />
    <parent link="base_link"/>
    <child link="plate_link" />
  </joint>
  <xacro:yuntai />

  <joint name="carmera_joint" type="fixed">
    <origin xyz=" 0 0.0315 -0.009 " rpy="-3.1415 0 0" />
    <parent link="top_link"/>
    <child link="kinect2" />
  </joint>
  <xacro:kinect2 />

<joint name="cover_plate_joint" type="fixed">
<origin xyz="-0.240 0 0.260" rpy="0 0 -1.571" />
<parent link="base_link" />
<child link="cover_plate_link" />
</joint>
<xacro:cover_plate />
  </xacro:macro>
</robot>
